### ISSUE TITLE
Mark llvm_asm calls as volatile

### ISSUE THREAD

**Issue by Yarn** [pusherofbrooms/avr-delay#13]
I'm pretty sure the llvm_asm invocation should be marked as volatile like
```rust
unsafe {llvm_asm!("1: sbiw $0,1
   brne 1b"
   :
   : "w" (0)
   :
   : "volatile")}
```

This could potentially explain https://github.com/avr-rust/delay/issues/11 and https://github.com/avr-rust/blink/issues/34 but I don't have an AVR device set up to test with.

**Comment by stappersg** [comment]
`llvm_asm!()` has been replaced with `asm!()`.
